### ISSUE TITLE
Any idea about making a generic DOM instead of just React

### ISSUE THREAD

**Issue by ClassicOldSong** [lvgl/lv_binding_js#8] opened 2022-12-11 10:56 UTC
It's good to see LVGL finally got a JS binding, but it's still a bit limited only binding to React. Is there any idea about making a generic DOM for LVGL so that other renderers like Svelte and SolidJS can easily bridge in?

There's an example of providing generic DOM to NativeScript: https://github.com/SudoMaker/dominative

And we got lots of existing web frameworks working on NativeScript without effort.

Also it's a good chance to get NativeScript integrated with LVGL through QuickJS.

**Comment by derekstavis** [comment] 2023-08-04 02:57
I feel like this is out of scope for the current state of this binding, as it's right now closer to React Native's approach to integration than NativeScript's approach. Probably this package should be renamed to `react-lvgl` to narrow the scope, and fork it to something like `nativescript-lvgl` to expose the DOM APIs

**Comment by ClassicOldSong** [comment] 2023-08-04 03:05
Never mind, I scratched my own itch though

DOM APIs are not contaminating anything since it's still provided by the same JS layer providing DOM to NativeScript.

https://twitter.com/classicoldsong/status/1632549846161948673

**Comment by derekstavis** [comment] 2023-08-04 03:54
Good job here! This is awesome! I'll go ahead and close this then!

**Comment by X-Ryl669** [comment] 2023-08-04 09:49
I don't really understand why you've closed this and #1. CheeseDOM is just a slideware as far as I know, there's nothing more than 2 (maybe fake) screenshots. It would be very interesting if it existed. Yet I don't think the issue is solved here.

**Comment by ClassicOldSong** [comment] 2023-08-04 13:17
I can promise that it’s as real as you are. We’re still adding more things
to the runtime(hardware interface like GPIO/SPI etc)

Just stay tuned.

**Comment by derekstavis** [comment] 2023-08-07 16:45
I gave some thought to this, and I think that long-term this binding should focus on exposing LVGL components in a JS-like API, and leave the framework plumbing to the user land, which could exist as a separate package.

For example, it should expose an API similar to this:

```
const object = new LVObject();
object.setBackgroundColor("#ff0000");

const style = new LVStyle();
style.setDisplay("flex");

object.setStyle(style);
```

**Comment by ClassicOldSong** [comment] 2023-08-07 18:41
Actually we have this done already, though manually. The DOM part is provided via [`undom-ng`](https://github.com/ClassicOldSong/undom-ng), while LVGL part is provided via CheeseGL(will be released alongside with Resonance, our JS runtime) for Resonance.

**Comment by ClassicOldSong** [comment] 2023-08-07 18:47
This is how part of the working code in one of our projects looks like:
```js
import { LVGL, Style } from 'cheesedom'

const style = {
	label: new Style({
		align: 'center',
		textAlign: 'center',
		width: '100%',
		textColor: '#ffffff',
	})
}

const goBack = () => {
	const indev = LVGL.indev_get_act()
	indev.wait_release()

	history.back()
}
```

**Comment by derekstavis** [comment] 2023-08-07 19:15
That's great news! Once you have it published, are you interested in discussing a way to merge the projects in a single one?

**Comment by kisvegabor** [comment] 2023-08-09 12:34
FYI, we we will publish our updated website which has this section in the home page. 
Thanks to @derekstavis, I can add the JS binding to the list. :slightly_smiling_face:  

![image](https://github.com/lvgl/lv_binding_js/assets/7599318/89f72623-4241-4d2b-b089-dea56744bd41)

**Comment by ClassicOldSong** [comment] 2023-08-09 19:06
> That's great news! Once you have it published, are you interested in discussing a way to merge the projects in a single one, and potentially make this an official binding featured on the website?

`CheeseGL` is a plugin for `Resonance` and `CheeseDOM` is a wrapper for `CheeseGL` using `undom-ng`, I'm afraid it can't be merged into one.

I'd like it to be featured but IDK if it meets your requirements.

**Comment by derekstavis** [comment] 2023-08-10 04:20
Let's evaluate once it's live :) I think we can find a middle ground that works for all potential abstractions. This way new functionalities in LVGL can always trickle down to client libraries

**Comment by derekstavis** [comment] 2024-08-09 04:48
I'm closing this issue since there seems to be a separate solution. Contributions to this binding are welcome though if there's interest in exposing bare LVGL APIs in txiki.js.

**Closed by derekstavis** 2024-08-09 04:48 UTC
